; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = PlatformIO version for BaahBoxArduino
default_envs = adafruit_feather_m0
src_dir      = src
include_dir  = src
extra_configs =
    ini/esp32S3.ini
    ini/FeatherM0Bluefruit.ini
	  ini/FeatherNRF52.ini

[common]
build_flags        = -D __DEBUG__

lib_deps           =
	arduino-libraries/SD@^1.2.4

default_src_filter = +<./*> +<./Config> +<./SD> +<BaahBox/BLE> +<./Sensors> +<./Display> 
  ; LCDs and Controllers
  -<./Display/ADA_TFT_SSD1306>
  -<./BLE/ESP32S3>
  -<./BLE/Nrf51> 
  -<./BLE/Nrf52>
  ;
  ; Minimal Requirements
  ;
 # +<src/module/tool_change.cpp>
  #+<src/module/stepper/indirection.cpp>

#
# Default values apply to all 'env:' prefixed environments
#
[env]
framework         = arduino
build_flags       = ${common.build_flags}
lib_deps          = ${common.lib_deps}
monitor_speed     = 115200
monitor_eol       = LF
monitor_echo      = yes
monitor_filters   = colorize, time, send_on_enter
