
[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
build_flags =  ${common.build_flags} -D USE_ESP32S3
  #  -include lib/uno/io_config.h
#build_unflags    = -std=gnu++11
build_src_filter = ${common.default_src_filter} +<BLE/ESP32S3> +<Display/ADA_TFT_SSD1306>
lib_deps =
 	${common.lib_deps}
    adafruit/Adafruit SSD1306@^2.5.7 // assuming we use the 'standard' FEATHER TFT 1306 featherwing as for the BlueFruit M0 or NRF52
	  adafruit/Adafruit GFX Library@^1.11.5
    # adafruit/Adafruit BNO08x RVC @ ^1.0.2
    #SoftwareSerialEsp32

debug_tool       = jlink
#lib_ignore        = NativeEthernet, AsyncTCP_RP2040W
#upload_speed      = 500000
monitor_speed     = 115200
monitor_filters   = colorize, time, send_on_enter, log2file, esp32_exception_decoder


[env:adafruit_feather_esp32s3_reverseTFT]
extends                = env:adafruit_feather_esp32s3
build_flags            = ${env:adafruit_feather_esp32s3.build_flags} 
board = adafruit_feather_esp32s3_reversetft
build_src_filter = ${common.default_src_filter} +<BLE/ESP32S3>  +<Display/ADA_ESP32_TFT>
lib_deps =
 	${common.lib_deps}
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
	  adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit MAX1704X @ ^1.0.3
    # adafruit/Adafruit BNO08x RVC @ ^1.0.2
    #SoftwareSerialEsp32
