[env:adafruit_feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
build_flags =  ${common.build_flags} -D USE_NRF52
    #-include lib/uno/io_config.h
#build_unflags    = -std=gnu++11
lib_deps =
 	${common.lib_deps}
    arduino-libraries/SD@^1.2.4
    adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit GFX Library@^1.11.5

build_src_filter = ${common.default_src_filter} +<BLE/Nrf52> +<Display/ADA_OLED_FEATHERWING>

#debug_tool       = jlink
#lib_ignore        = NativeEthernet, AsyncTCP_RP2040W
#upload_speed      = 500000
monitor_speed     = 115200
monitor_filters   = colorize, time, send_on_enter, log2file
